#' catboost - parameter tuning and model selection with k-fold cross-validation and grid search
#'
#' @param x Predictor matrix.
#' @param y Response vector.
#' @param params Parameter grid generated by [cv_param_grid()].
#' @param nfolds Number of folds. Default is 5.
#' @param seed Random seed for reproducibility.
#' @param verbose Show progress?
#' @param ncpus Number of CPU cores to use. Defaults is all detectable cores.
#'
#' @return A data frame containing the complete tuning grid and the AUC values,
#'   with the best parameter combination and the highest AUC value.
#'
#' @export
#'
#' @examples
#' # check the vignette for code examples
cv_catboost <- function(
    x, y,
    params = cv_param_grid(),
    nfolds = 5L,
    seed = 42,
    verbose = TRUE,
    ncpus = parallel::detectCores()) {
  params <- map_params_catboost(params)

  set.seed(seed)
  nrow_x <- nrow(x)
  index <- sample(rep_len(1L:nfolds, nrow_x))
  df_grid <- expand.grid(
    "iterations" = params$iterations,
    "depth" = params$depth,
    "metric" = NA
  )
  nrow_grid <- nrow(df_grid)

  # x <- as.matrix(x) # uncomment to use non-categorical features

  pb <- progress_bar$new(
    format = "  searching grid [:bar] :percent in :elapsed",
    total = nrow_grid * nfolds, clear = FALSE, width = 60
  )

  for (j in 1L:nrow_grid) {
    ypred <- matrix(NA, ncol = 2L, nrow = nrow_x)
    for (i in 1L:nfolds) {
      if (verbose) pb$tick()

      xtrain <- x[index != i, , drop = FALSE]
      ytrain <- y[index != i]
      xtest <- x[index == i, , drop = FALSE]
      ytest <- y[index == i]

      train_pool <- catboost_load_pool(data = xtrain, label = ytrain)
      test_pool <- catboost_load_pool(data = xtest, label = NULL)
      fit <- catboost_train(
        train_pool,
        test_pool = NULL,
        params = list(
          loss_function = "Logloss",
          iterations = df_grid[j, "iterations"],
          depth = df_grid[j, "depth"],
          logging_level = "Silent",
          thread_count = ncpus
        )
      )
      ypredvec <- catboost_predict(fit, pool = test_pool, prediction_type = "Probability")
      ypred[index == i, 1L] <- ytest
      ypred[index == i, 2L] <- ypredvec
    }
    colnames(ypred) <- c("y.real", "y.pred")
    df_grid[j, "metric"] <- as.numeric(pROC::auc(ypred[, "y.real"], ypred[, "y.pred"], quiet = TRUE))
  }

  best_row <- which.max(df_grid$metric)
  best_metric <- df_grid$metric[best_row]
  best_iterations <- df_grid$iterations[best_row]
  best_depth <- df_grid$depth[best_row]

  list(
    df = df_grid,
    metric = best_metric,
    iterations = best_iterations,
    depth = best_depth
  )
}
