#' lightgbm - parameter tuning and model selection with k-fold cross-validation
#' and grid search
#'
#' @param x Predictor matrix.
#' @param y Response vector.
#' @param params Parameter grid generated by [cv_param_grid()].
#' @param nfolds Number of folds. Default is 5.
#' @param seed Random seed for reproducibility.
#' @param verbose Show progress?
#' @param ncpus Number of CPU cores to use. Defaults is all detectable cores.
#'
#' @return A data frame containing the complete tuning grid and the AUC values,
#'   with the best parameter combination and the highest AUC value.
#'
#' @export
#'
#' @examples
#' # check the vignette for code examples
cv_lightgbm <- function(
    x, y,
    params = cv_param_grid(),
    nfolds = 5L,
    seed = 42,
    verbose = TRUE,
    ncpus = parallel::detectCores()) {
  params <- map_params_lightgbm(params)

  set.seed(seed)
  nrow_x <- nrow(x)
  index <- sample(rep_len(1L:nfolds, nrow_x))
  df_grid <- expand.grid(
    "num_iterations" = params$num_iterations,
    "max_depth" = params$max_depth,
    "learning_rate" = params$learning_rate,
    "metric" = NA
  )
  nrow_grid <- nrow(df_grid)

  x <- as.matrix(x)

  pb <- progress_bar$new(
    format = "  searching grid [:bar] :percent in :elapsed",
    total = nrow_grid * nfolds, clear = FALSE, width = 60
  )

  for (j in 1L:nrow_grid) {
    ypred <- matrix(NA, ncol = 2L, nrow = nrow_x)
    for (i in 1L:nfolds) {
      if (verbose) pb$tick()

      xtrain <- x[index != i, , drop = FALSE]
      ytrain <- y[index != i]
      xtest <- x[index == i, , drop = FALSE]
      ytest <- y[index == i]

      fit <- lightgbm_train(
        data = xtrain,
        label = ytrain,
        params = list(
          objective = "binary",
          learning_rate = df_grid[j, "learning_rate"],
          num_iterations = df_grid[j, "num_iterations"],
          max_depth = df_grid[j, "max_depth"],
          num_leaves = 2^(df_grid[j, "max_depth"]) - 1,
          num_threads = ncpus
        ),
        verbose = -1
      )
      ypredvec <- predict(fit, xtest)
      ypred[index == i, 1L] <- ytest
      ypred[index == i, 2L] <- ypredvec
    }
    colnames(ypred) <- c("y.real", "y.pred")
    df_grid[j, "metric"] <- as.numeric(pROC::auc(ypred[, "y.real"], ypred[, "y.pred"], quiet = TRUE))
  }

  best_row <- which.max(df_grid$metric)
  best_metric <- df_grid$metric[best_row]
  best_num_iterations <- df_grid$num_iterations[best_row]
  best_max_depth <- df_grid$max_depth[best_row]
  best_learning_rate <- df_grid$learning_rate[best_row]

  list(
    df = df_grid,
    metric = best_metric,
    num_iterations = best_num_iterations,
    max_depth = best_max_depth,
    learning_rate = best_learning_rate
  )
}
